### 網頁爬蟲

今天我們先教最簡單的一種，之後我們會碰到各種不同的情況，
今天這招幾乎可以破解60%以上的網頁

首先我們要先import requests，可以把它想像成是瀏覽器

In [14]:
import requests

res = requests.get('https://www.w3schools.com/html/html_tables.asp')

### 網頁代碼

取得網頁的原始碼

In [15]:
res.text

'\n<!DOCTYPE html>\n<html lang="en-US">\n<head>\n<title>HTML Tables</title>\n<meta charset="utf-8">\n<meta name="viewport" content="width=device-width, initial-scale=1">\n<meta name="title" property="og:title" content="W3Schools.com">\n<meta name="Keywords" content="HTML, Python, CSS, SQL, JavaScript, How to, PHP, Java, C, C++, C#, jQuery, Bootstrap, Colors, W3.CSS, XML, MySQL, Icons, NodeJS, React, Graphics, Angular, R, AI, Git, Data Science, Code Game, Tutorials, Programming, Web Development, Training, Learning, Quiz, Exercises, Courses, Lessons, References, Examples, Learn to code, Source code, Demos, Tips, Website">\n<meta name="Description" content="Well organized and easy to understand Web building tutorials with lots of examples of how to use HTML, CSS, JavaScript, SQL, Python, PHP, Bootstrap, Java, XML and more.">\n<meta property="og:image" content="https://www.w3schools.com/images/w3schools_logo_436_2.png">\n<meta property="og:image:type" content="image/png">\n<meta property="og:image:width" content="436">\n<meta property="og:image:height" content="228">\n<meta property="og:description" content="W3Schools offers free online tutorials, references and exercises in all the major languages of the web. Covering popular subjects like HTML, CSS, JavaScript, Python, SQL, Java, and many, many more.">\n<link rel="icon" href="https://www.w3schools.com/favicon.ico">\n<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">\n<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">\n<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">\n<link rel="manifest" href="/site.webmanifest" crossorigin="use-credentials">\n<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#04aa6d">\n<meta name="msapplication-TileColor" content="#00a300">\n<meta name="theme-color" content="#ffffff">\n<meta name="format-detection" content="telephone=no">\n<link rel="preload" href="/lib/fonts/fontawesome.woff2?14663396" as="font" type="font/woff2" crossorigin> \n<link rel="preload" href="/lib/fonts/source-code-pro-v14-latin-regular.woff2" as="font" type="font/woff2" crossorigin> \n<link rel="preload" href="/lib/fonts/roboto-mono-v13-latin-500.woff2" as="font" type="font/woff2" crossorigin> \n<link rel="preload" href="/lib/fonts/source-sans-pro-v14-latin-700.woff2" as="font" type="font/woff2" crossorigin> \n<link rel="preload" href="/lib/fonts/source-sans-pro-v14-latin-600.woff2" as="font" type="font/woff2" crossorigin>\n<link rel="preload" href="/lib/fonts/SourceSansPro-Regular.woff2" as="font" type="font/woff2" crossorigin>\n<link rel="preload" href="/lib/fonts/freckle-face-v9-latin-regular.woff2" as="font" type="font/woff2" crossorigin> \n<link rel="stylesheet" href="/lib/topnav/main.v1.0.100.css">\n<link rel="stylesheet" href="/lib/my-learning/main.v1.0.86.css">\n<link rel="stylesheet" href="/lib/pathfinder/main.v1.0.12.css">\n<link rel="stylesheet" href="/lib/w3schools.css?v=1.0.1">\n<link rel="stylesheet" href="/plus/plans/main.v1.0.3.css">\n<link rel="stylesheet" href="/lib/sparteo.css?v=1.0.5">\n<script data-cfasync=false data-no-optimize=1 data-wpmeteor-nooptimize=true nowprocket>window.FAST_CMP_OPTIONS={domainUid:"849c868d-5fd6-58f9-8963-b1468ae3b279",countryCode:"NO",jurisdiction:"tcfeuv2",customOpener: true,policyUrl:"https://www.w3schools.com/about/about_privacy.asp",displaySynchronous:!1,publisherName:"W3Schools",publisherLogo:function(r){return r.createElement("img",{src:"https://www.w3schools.com/images/w3schools_logo_500_04AA6D.webp",height:"40"})},bootstrap:{excludedIABVendors:[],excludedGoogleVendors:[]},custom:{vendors:[]},},function(){var o={484:function(r){window.FAST_CMP_T0=Date.now(),window.FAST_CMP_QUEUE={},window.FAST_CMP_QUEUE_ID=0,r.exports={name:"light",handler:function(){var r=Array.prototype.slice.call(arguments);if(!r.length)return Object.values(window.FAST_CMP_QUEUE);"ping"===r[0]?"function"==typeof r[2]&&r[2]({cmpLoaded:!1,cmpStatus:"stub",apiVersion:"2.0",cmpId:parseInt("388",10)}):window.FAST_CMP_QUEUE[window.FAST_CMP_QUEUE_ID++]=r}}}},n={};function e(r){return(e="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(r){return typeof r}:function(r){return r&&"function"==typeof Symbol&&r.constructor===Symbol&&r!==Symbol.prototype?"symbol":typeof r})(r)}var r,a=function r(e){var a=n[e];if(void 0!==a)return a.exports;var t=n[e]={exports:{}};return o[e](t,t.exports,r),t.exports}(484),i="__tcfapiLocator",c=window,t=c;for(;t;){try{if(t.frames[i]){r=t;break}}catch(o){}if(t===c.top)break;t=t.parent}if("custom"!==c.FAST_CMP_HANDLER)for(var s in r?(c.__tcfapi=a.handler,c.FAST_CMP_HANDLER=a.name):(function r(){var e=c.document,a=!!c.frames[i];if(!a)if(e.body){var t=e.createElement("iframe");t.style.cssText="display:none",t.name=i,e.body.appendChild(t)}else setTimeout(r,5);return!a}(),c.__tcfapi=a.handler,c.FAST_CMP_HANDLER=a.name,c.addEventListener("message",function(t){var o="string"==typeof t.data,r={};if(o)try{r=JSON.parse(t.data)}catch(t){}else r=t.data;var n="object"===e(r)?r.__tcfapiCall:null;n&&window.__tcfapi(n.command,n.version,function(r,e){var a={__tcfapiReturn:{returnValue:r,success:e,callId:n.callId}};t&&t.source&&t.source.postMessage&&t.source.postMessage(o?JSON.stringify(a):a,"*")},n.parameter)},!1)),window.FAST_CMP_QUEUE||{})c.__tcfapi.apply(null,window.FAST_CMP_QUEUE[s])}()</script>\n<script data-cfasync=false data-no-optimize=1 data-wpmeteor-nooptimize=true nowprocket async charset=UTF-8 src=https://static.fastcmp.com/fast-cmp-stub.js></script>\n<style>\n#nav_tutorials,#nav_references,#nav_certified,#nav_services,#nav_exercises {display:none;letter-spacing:0;position:absolute;width:100%;background-color:#282A35;color:white;padding-bottom:40px;z-index: 5 !important;font-family: \'Source Sans Pro Topnav\', sans-serif !important;}\n</style>\n\n<!-- Google Tag Manager -->\n<script>\n(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({\'gtm.start\':\nnew Date().getTime(),event:\'gtm.js\'});var f=d.getElementsByTagName(s)[0],\nj=d.createElement(s),dl=l!=\'dataLayer\'?\'&l=\'+l:\'\';j.async=true;j.src=\n\'https://www.googletagmanager.com/gtm.js?id=\'+i+dl;f.parentNode.insertBefore(j,f);\n})(window,document,\'script\',\'dataLayer\',\'GTM-KTCFC3S\');\n\nvar subjectFolder = location.pathname;\nsubjectFolder = subjectFolder.replace("/", "");\nif (subjectFolder.startsWith("python/") == true ) {\n  if (subjectFolder.includes("/numpy/") == true ) {\n    subjectFolder = "numpy/"\n  } else if (subjectFolder.includes("/pandas/") == true ) {\n      subjectFolder = "pandas/"\n  } else if (subjectFolder.includes("/scipy/") == true ) {\n      subjectFolder = "scipy/"\n  }\n}\nsubjectFolder = subjectFolder.substr(0, subjectFolder.indexOf("/"));\n</script>\n<!-- End Google Tag Manager -->\n<script src="/lib/uic.js?v=1.1.0"></script>\n<script src="/lib/uic_prov.js?v=1.5.0"></script>\n\n<script data-cfasync="false" type="text/javascript">\n\nuic_prov_pre("default","",subjectFolder);\nvar stickyadstatus = "";\nfunction fix_stickyad() {\n  document.getElementById("stickypos").style.position = "sticky";\n  var elem = document.getElementById("stickyadcontainer");\n  if (!elem) {return false;}\n  if (document.getElementById("skyscraper")) {\n    var skyWidth = Number(w3_getStyleValue(document.getElementById("skyscraper"), "width").replace("px", ""));\n    if (isNaN(skyWidth) && document.getElementById("upperfeatureshowcaselink").parentElement) {\n      skyWidth = Number(w3_getStyleValue(document.getElementById("upperfeatureshowcaselink").parentElement, "width").replace("px", ""));\n    }\n  }\n  else {\n    var skyWidth = Number(w3_getStyleValue(document.getElementById("right"), "width").replace("px", ""));  \n  }\n  elem.style.width = skyWidth + "px";\n  if (window.innerWidth <= 992) {\n    elem.style.position = "";\n    elem.style.top = stickypos + "px";\n    return false;\n  }\n  var stickypos = document.getElementById("stickypos").offsetTop;\n  var docTop = window.pageYOffset || document.documentElement.scrollTop || document.body.scrollTop;\n  var adHeight = Number(w3_getStyleValue(elem, "height").replace("px", ""));\n  if (stickyadstatus == "") {\n    if ((stickypos - docTop) < 100) {\n      elem.style.position = "fixed";\n      elem.style.top = "100px";\n      stickyadstatus = "sticky";\n      document.getElementById("stickypos").style.position = "sticky";\n\n    }\n  } else {\n    if ((docTop + 100) - stickypos < 0) {  \n      elem.style.position = "";\n      elem.style.top = stickypos + "px";\n      stickyadstatus = "";\n      document.getElementById("stickypos").style.position = "static";\n    }\n  }\n  if (stickyadstatus == "sticky") {\n    if ((docTop + adHeight + 100) > document.getElementById("footer").offsetTop) {\n      elem.style.position = "absolute";\n      elem.style.top = (document.getElementById("footer").offsetTop - adHeight) + "px";\n      document.getElementById("stickypos").style.position = "static";\n    } else {\n        elem.style.position = "fixed";\n        elem.style.top = "100px";\n        stickyadstatus = "sticky";\n        document.getElementById("stickypos").style.position = "sticky";\n    }\n  }\n}\nfunction w3_getStyleValue(elmnt,style) {\n  if (window.getComputedStyle) {\n    return window.getComputedStyle(elmnt,null).getPropertyValue(style);\n  } else {\n    return elmnt.currentStyle[style];\n  }\n}\n</script>\n\n<script src="/lib/common-deps/main.v1.0.18.js"></script>\n<script src="/lib/user-session/main.v1.0.51.js"></script>\n<script src="/lib/topnav/main.v1.0.100.js"></script>\n<script src="/lib/my-learning/main.v1.0.86.js"></script>\n\n<style>\ntable#customers {\n    font-family: arial, sans-serif;\n    border-collapse: collapse;\n    width: 100%;\n}\n\n#customers td, #customers th {\n    border: 1px solid #dddddd;\n    text-align: left;\n    padding: 8px;\n}\n\n.tryiticon {\n  background-color: #4CAF50;\n  color: #fff!important;\n  text-decoration: none;\n  padding: 0 8px 4px 8px;\n  border-radius: 50px;\n  font-size: 15px;\n  position: absolute;\n  margin-left: 6px;\n  transition: padding 0.2s;\n  \n}\n.tryiticon span{\n  color:#fff!important;\n  font-size:14px;\n  font-weight:normal;\n  position:absolute;\n  width:0px;\n  overflow:hidden;\n  transition: width 0.2;\n}\n\n.tryiticon:hover {\n  padding:0 12px 4px 116px;\n}\n\n.tryiticon:hover span{\n  width:116px;\n  padding-top:2px;\n  left:10px;\n}\n\n.htmltut_table, .htmltut_table th, .htmltut_table td\n{\nborder:1px solid black;\n}\n.htmltut_table1, .htmltut_table1 th, .htmltut_table1 td\n{\nborder:1px solid black;\n}\n.htmltut_table1 th, .htmltut_table1 td\n{\npadding:5px;\n}\n</style>\n</head>\n<body>\n\n<div id="tnb-search-suggestions"></div>\n<div\n  id="top-nav-bar"\n  class="classic"\n>\n  <div\n    id="pagetop"\n    class="w3-bar notranslate w3-white"\n  >\n    <a\n      id="w3-logo"\n      href="https://www.w3schools.com"\n      class="w3-bar-item w3-button w3-hover-none w3-left ga-top ga-top-w3home"\n      title="Home"\n      aria-label="Home link"\n    >\n      <i\n        class="fa fa-logo ws-hover-text-green"\n        aria-hidden="true"\n      ></i>\n    </a>\n    <nav class="tnb-desktop-nav w3-bar-item">\n      <a\n        onclick="TopNavBar.openNavItem(\'tutorials\')"\n        class="tnb-nav-btn w3-bar-item w3-button barex bar-item-hover w3-padding-16 ga-top ga-top-tut-and-ref"\n        href="javascript:void(0)"\n        id="navbtn_tutorials"\n        title="Tutorials and References"\n        role="button"\n      >\n        Tutorials\n        <i\n          class="fa fa-caret-down"\n          style="font-size: 15px"\n          aria-hidden="true"\n        ></i>\n        <i\n          class="fa fa-caret-up"\n          style="display: none; font-size: 15px"\n          aria-hidden="true"\n        ></i>\n      </a>\n      <a\n        onclick="TopNavBar.openNavItem(\'references\')"\n        class="tnb-nav-btn w3-bar-item w3-button barex bar-item-hover w3-padding-16 ga-top ga-top-ref"\n        href="javascript:void(0)"\n        id="navbtn_references"\n        title="References"\n        role="button"\n      >\n        References\n        <i\n          class="fa fa-caret-down"\n          style="font-size: 15px"\n          aria-hidden="true"\n        ></i>\n        <i\n          class="fa fa-caret-up"\n          style="display: none; font-size: 15px"\n          aria-hidden="true"\n        ></i>\n      </a>\n      <a\n        onclick="TopNavBar.openNavItem(\'exercises\')"\n        class="tnb-nav-btn w3-bar-item w3-button barex bar-item-hover w3-padding-16 ga-top ga-top-exc-and-quz"\n        href="javascript:void(0)"\n        id="navbtn_exercises"\n        title="Exercises and Quizzes"\n        role="button"\n      >\n        Exercises\n        <i\n          class="fa fa-caret-down"\n          style="font-size: 15px"\n          aria-hidden="true"\n        ></i>\n        <i\n          class="fa fa-caret-up"\n          style="display: none; font-size: 15px"\n          aria-hidden="true"\n        ></i>\n      </a>\n      <a\n        onclick="TopNavBar.openNavItem(\'certified\')"\n        class="tnb-nav-btn w3-bar-item w3-button barex bar-item-hover w3-padding-16 tnb-paid-service ga-top ga-top-cert-and-course"\n        href="javascript:void(0)"\n        id="navbtn_certified"\n        title="Certificates"\n        role="button"\n      >\n        Certificates\n        <i\n          class="fa fa-caret-down"\n          style="font-size: 15px"\n          aria-hidden="true"\n        ></i>\n        <i\n          class="fa fa-caret-up"\n          style="display: none; font-size: 15px"\n          aria-hidden="true"\n        ></i>\n      </a>\n    </nav>\n    <a\n      onclick="TopNavBar.openMenu()"\n      class="tnb-menu-btn w3-bar-item w3-button bar-item-hover w3-padding-16 ga-top ga-top-menu"\n      href="javascript:void(0)"\n      title="Menu"\n      aria-label="Menu"\n      role="button"\n    >\n      Menu\n      <i\n        class="fa fa-caret-down"\n        style="font-size: 15px"\n        aria-hidden="true"\n      ></i>\n      <i\n        class="fa fa-caret-up"\n        style="display: none; font-size: 15px"\n        aria-hidden="true"\n      ></i>\n    </a>\n    <div\n      id="tnb-google-search-container"\n      class="w3-bar-item"\n    >\n      <div id="tnb-google-search-inner-container">\n        <label\n          for="tnb-google-search-input"\n          class="tnb-soft-hide"\n        >\n          Search field\n        </label>\n        <input\n          id="tnb-google-search-input"\n          type="text"\n          placeholder="Search..."\n          autocomplete="off"\n          onkeydown="TopNavBar.googleSearchAttachKeyPressHandler(event)"\n          aria-label="Search field"\n          oninput="TopNavBar.searchWithSuggestions(this)"\n          onfocus="TopNavBar.searchWithSuggestions(this)"\n          onblur="TopNavBar.searchFieldLostFocus(event)"\n        />\n        <div\n          id="tnb-google-search-submit-btn"\n          class="tnb-button-light"\n          role="button"\n          aria-label="Button to search"\n          onclick="TopNavBar.googleSearchSubmit()"\n        >\n          <svg\n            id="tnb-google-search-icon"\n            viewBox="0 0 17 16"\n            fill="none"\n            xmlns="http://www.w3.org/2000/svg"\n          >\n            <path\n              d="M11.8153 10.3439C12.6061 9.2673 13.0732 7.9382 13.0732 6.5C13.0732 2.91015 10.163 0 6.57318 0C2.98333 0 0.0731812 2.91015 0.0731812 6.5C0.0731812 10.0899 2.98333 13 6.57318 13C8.01176 13 9.3412 12.5327 10.4179 11.7415L10.4171 11.7422C10.4466 11.7822 10.4794 11.8204 10.5156 11.8566L14.3661 15.7071C14.7566 16.0976 15.3898 16.0976 15.7803 15.7071C16.1708 15.3166 16.1708 14.6834 15.7803 14.2929L11.9298 10.4424C11.8936 10.4062 11.8553 10.3734 11.8153 10.3439ZM12.0732 6.5C12.0732 9.53757 9.61075 12 6.57318 12C3.53561 12 1.07318 9.53757 1.07318 6.5C1.07318 3.46243 3.53561 1 6.57318 1C9.61075 1 12.0732 3.46243 12.0732 6.5Z"\n              fill="black"\n            ></path>\n          </svg>\n        </div>\n      </div>\n      <div id="tnb-google-search-mobile-action-btns">\n        <div\n          id="tnb-google-search-mobile-show"\n          class="tnb-button"\n          onclick="TopNavBar.googleSearchShowMobileContainer()"\n          aria-label="Button to open search field"\n          role="button"\n        >\n          <svg\n            viewBox="0 0 17 16"\n            fill="none"\n            xmlns="http://www.w3.org/2000/svg"\n          >\n            <path\n              d="M11.8153 10.3439C12.6061 9.2673 13.0732 7.9382 13.0732 6.5C13.0732 2.91015 10.163 0 6.57318 0C2.98333 0 0.0731812 2.91015 0.0731812 6.5C0.0731812 10.0899 2.98333 13 6.57318 13C8.01176 13 9.3412 12.5327 10.4179 11.7415L10.4171 11.7422C10.4466 11.7822 10.4794 11.8204 10.5156 11.8566L14.3661 15.7071C14.7566 16.0976 15.3898 16.0976 15.7803 15.7071C16.1708 15.3166 16.1708 14.6834 15.7803 14.2929L11.9298 10.4424C11.8936 10.4062 11.8553 10.3734 11.8153 10.3439ZM12.0732 6.5C12.0732 9.53757 9.61075 12 6.57318 12C3.53561 12 1.07318 9.53757 1.07318 6.5C1.07318 3.46243 3.53561 1 6.57318 1C9.61075 1 12.0732 3.46243 12.0732 6.5Z"\n              fill="currentColor"\n            ></path>\n          </svg>\n        </div>\n        <div\n          id="tnb-google-search-mobile-close"\n          class="tnb-button"\n          onclick="TopNavBar.googleSearchHideMobileContainer()"\n          role="button"\n          aria-label="Close search field"\n        >\n          <i>&times;</i>\n        </div>\n      </div>\n    </div>\n    <div id="tnb-menu-toggle-wrapper">\n      <a\n        onclick="TopNavBar.openNavItem(\'services\')"\n        class="tnb-nav-btn w3-bar-item w3-button barex bar-item-hover ga-top ga-top-services w3-tooltip"\n        href="javascript:void(0)"\n        id="navbtn_services"\n        aria-label="All our services"\n        role="button"\n      >\n        <span\n          class="w3-text"\n          id="button-to-open-services"\n        >\n          See More\n        </span>\n        <svg\n          xmlns="http://www.w3.org/2000/svg"\n          viewBox="0 0 640 640"\n        >\n          <path d="M320 208C289.1 208 264 182.9 264 152C264 121.1 289.1 96 320 96C350.9 96 376 121.1 376 152C376 182.9 350.9 208 320 208zM320 432C350.9 432 376 457.1 376 488C376 518.9 350.9 544 320 544C289.1 544 264 518.9 264 488C264 457.1 289.1 432 320 432zM376 320C376 350.9 350.9 376 320 376C289.1 376 264 350.9 264 320C264 289.1 289.1 264 320 264C350.9 264 376 289.1 376 320z" />\n        </svg>\n        <span style="font-size: 120px">&nbsp;</span>\n        <i aria-hidden="true"></i>\n        <i aria-hidden="true"></i>\n      </a>\n    </div>\n    <div class="tnb-right-section">\n      <!-- < user-anonymous -->\n      <div\n        id="tnb-login-btn"\n        class="user-anonymous tnb-login-btn w3-bar-item w3-btn w3-hide bar-item-hover w3-right w3s-green ga-top ga-top-login"\n        title="Sign in to your account"\n        aria-label="Sign in to your account"\n        tabindex="0"\n        role="button"\n      >\n        <svg\n          width="14"\n          height="14"\n          viewBox="0 0 14 14"\n          fill="none"\n          xmlns="http://www.w3.org/2000/svg"\n          class="tnb-sign-in-icon"\n        >\n          <path\n            d="M7 7C8.933 7 10.5 5.433 10.5 3.5C10.5 1.567 8.933 0 7 0C5.067 0 3.5 1.567 3.5 3.5C3.5 5.433 5.067 7 7 7ZM9.33333 3.5C9.33333 4.78866 8.28866 5.83333 7 5.83333C5.71134 5.83333 4.66667 4.78866 4.66667 3.5C4.66667 2.21134 5.71134 1.16667 7 1.16667C8.28866 1.16667 9.33333 2.21134 9.33333 3.5Z"\n            fill="white"\n          />\n          <path\n            d="M14 12.8333C14 14 12.8333 14 12.8333 14H1.16667C1.16667 14 0 14 0 12.8333C0 11.6667 1.16667 8.16667 7 8.16667C12.8333 8.16667 14 11.6667 14 12.8333ZM12.8333 12.8293C12.8316 12.5414 12.6539 11.6789 11.8625 10.8875C11.1016 10.1265 9.67062 9.33333 6.99999 9.33333C4.32936 9.33333 2.89841 10.1265 2.13745 10.8875C1.34605 11.6789 1.16833 12.5414 1.16

### 轉碼

In [16]:
res.encoding = 'utf-8'  # 'big5'
res.text

'\n<!DOCTYPE html>\n<html lang="en-US">\n<head>\n<title>HTML Tables</title>\n<meta charset="utf-8">\n<meta name="viewport" content="width=device-width, initial-scale=1">\n<meta name="title" property="og:title" content="W3Schools.com">\n<meta name="Keywords" content="HTML, Python, CSS, SQL, JavaScript, How to, PHP, Java, C, C++, C#, jQuery, Bootstrap, Colors, W3.CSS, XML, MySQL, Icons, NodeJS, React, Graphics, Angular, R, AI, Git, Data Science, Code Game, Tutorials, Programming, Web Development, Training, Learning, Quiz, Exercises, Courses, Lessons, References, Examples, Learn to code, Source code, Demos, Tips, Website">\n<meta name="Description" content="Well organized and easy to understand Web building tutorials with lots of examples of how to use HTML, CSS, JavaScript, SQL, Python, PHP, Bootstrap, Java, XML and more.">\n<meta property="og:image" content="https://www.w3schools.com/images/w3schools_logo_436_2.png">\n<meta property="og:image:type" content="image/png">\n<meta property="og:image:width" content="436">\n<meta property="og:image:height" content="228">\n<meta property="og:description" content="W3Schools offers free online tutorials, references and exercises in all the major languages of the web. Covering popular subjects like HTML, CSS, JavaScript, Python, SQL, Java, and many, many more.">\n<link rel="icon" href="https://www.w3schools.com/favicon.ico">\n<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">\n<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">\n<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">\n<link rel="manifest" href="/site.webmanifest" crossorigin="use-credentials">\n<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#04aa6d">\n<meta name="msapplication-TileColor" content="#00a300">\n<meta name="theme-color" content="#ffffff">\n<meta name="format-detection" content="telephone=no">\n<link rel="preload" href="/lib/fonts/fontawesome.woff2?14663396" as="font" type="font/woff2" crossorigin> \n<link rel="preload" href="/lib/fonts/source-code-pro-v14-latin-regular.woff2" as="font" type="font/woff2" crossorigin> \n<link rel="preload" href="/lib/fonts/roboto-mono-v13-latin-500.woff2" as="font" type="font/woff2" crossorigin> \n<link rel="preload" href="/lib/fonts/source-sans-pro-v14-latin-700.woff2" as="font" type="font/woff2" crossorigin> \n<link rel="preload" href="/lib/fonts/source-sans-pro-v14-latin-600.woff2" as="font" type="font/woff2" crossorigin>\n<link rel="preload" href="/lib/fonts/SourceSansPro-Regular.woff2" as="font" type="font/woff2" crossorigin>\n<link rel="preload" href="/lib/fonts/freckle-face-v9-latin-regular.woff2" as="font" type="font/woff2" crossorigin> \n<link rel="stylesheet" href="/lib/topnav/main.v1.0.100.css">\n<link rel="stylesheet" href="/lib/my-learning/main.v1.0.86.css">\n<link rel="stylesheet" href="/lib/pathfinder/main.v1.0.12.css">\n<link rel="stylesheet" href="/lib/w3schools.css?v=1.0.1">\n<link rel="stylesheet" href="/plus/plans/main.v1.0.3.css">\n<link rel="stylesheet" href="/lib/sparteo.css?v=1.0.5">\n<script data-cfasync=false data-no-optimize=1 data-wpmeteor-nooptimize=true nowprocket>window.FAST_CMP_OPTIONS={domainUid:"849c868d-5fd6-58f9-8963-b1468ae3b279",countryCode:"NO",jurisdiction:"tcfeuv2",customOpener: true,policyUrl:"https://www.w3schools.com/about/about_privacy.asp",displaySynchronous:!1,publisherName:"W3Schools",publisherLogo:function(r){return r.createElement("img",{src:"https://www.w3schools.com/images/w3schools_logo_500_04AA6D.webp",height:"40"})},bootstrap:{excludedIABVendors:[],excludedGoogleVendors:[]},custom:{vendors:[]},},function(){var o={484:function(r){window.FAST_CMP_T0=Date.now(),window.FAST_CMP_QUEUE={},window.FAST_CMP_QUEUE_ID=0,r.exports={name:"light",handler:function(){var r=Array.prototype.slice.call(arguments);if(!r.length)return Object.values(window.FAST_CMP_QUEUE);"ping"===r[0]?"function"==typeof r[2]&&r[2]({cmpLoaded:!1,cmpStatus:"stub",apiVersion:"2.0",cmpId:parseInt("388",10)}):window.FAST_CMP_QUEUE[window.FAST_CMP_QUEUE_ID++]=r}}}},n={};function e(r){return(e="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(r){return typeof r}:function(r){return r&&"function"==typeof Symbol&&r.constructor===Symbol&&r!==Symbol.prototype?"symbol":typeof r})(r)}var r,a=function r(e){var a=n[e];if(void 0!==a)return a.exports;var t=n[e]={exports:{}};return o[e](t,t.exports,r),t.exports}(484),i="__tcfapiLocator",c=window,t=c;for(;t;){try{if(t.frames[i]){r=t;break}}catch(o){}if(t===c.top)break;t=t.parent}if("custom"!==c.FAST_CMP_HANDLER)for(var s in r?(c.__tcfapi=a.handler,c.FAST_CMP_HANDLER=a.name):(function r(){var e=c.document,a=!!c.frames[i];if(!a)if(e.body){var t=e.createElement("iframe");t.style.cssText="display:none",t.name=i,e.body.appendChild(t)}else setTimeout(r,5);return!a}(),c.__tcfapi=a.handler,c.FAST_CMP_HANDLER=a.name,c.addEventListener("message",function(t){var o="string"==typeof t.data,r={};if(o)try{r=JSON.parse(t.data)}catch(t){}else r=t.data;var n="object"===e(r)?r.__tcfapiCall:null;n&&window.__tcfapi(n.command,n.version,function(r,e){var a={__tcfapiReturn:{returnValue:r,success:e,callId:n.callId}};t&&t.source&&t.source.postMessage&&t.source.postMessage(o?JSON.stringify(a):a,"*")},n.parameter)},!1)),window.FAST_CMP_QUEUE||{})c.__tcfapi.apply(null,window.FAST_CMP_QUEUE[s])}()</script>\n<script data-cfasync=false data-no-optimize=1 data-wpmeteor-nooptimize=true nowprocket async charset=UTF-8 src=https://static.fastcmp.com/fast-cmp-stub.js></script>\n<style>\n#nav_tutorials,#nav_references,#nav_certified,#nav_services,#nav_exercises {display:none;letter-spacing:0;position:absolute;width:100%;background-color:#282A35;color:white;padding-bottom:40px;z-index: 5 !important;font-family: \'Source Sans Pro Topnav\', sans-serif !important;}\n</style>\n\n<!-- Google Tag Manager -->\n<script>\n(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({\'gtm.start\':\nnew Date().getTime(),event:\'gtm.js\'});var f=d.getElementsByTagName(s)[0],\nj=d.createElement(s),dl=l!=\'dataLayer\'?\'&l=\'+l:\'\';j.async=true;j.src=\n\'https://www.googletagmanager.com/gtm.js?id=\'+i+dl;f.parentNode.insertBefore(j,f);\n})(window,document,\'script\',\'dataLayer\',\'GTM-KTCFC3S\');\n\nvar subjectFolder = location.pathname;\nsubjectFolder = subjectFolder.replace("/", "");\nif (subjectFolder.startsWith("python/") == true ) {\n  if (subjectFolder.includes("/numpy/") == true ) {\n    subjectFolder = "numpy/"\n  } else if (subjectFolder.includes("/pandas/") == true ) {\n      subjectFolder = "pandas/"\n  } else if (subjectFolder.includes("/scipy/") == true ) {\n      subjectFolder = "scipy/"\n  }\n}\nsubjectFolder = subjectFolder.substr(0, subjectFolder.indexOf("/"));\n</script>\n<!-- End Google Tag Manager -->\n<script src="/lib/uic.js?v=1.1.0"></script>\n<script src="/lib/uic_prov.js?v=1.5.0"></script>\n\n<script data-cfasync="false" type="text/javascript">\n\nuic_prov_pre("default","",subjectFolder);\nvar stickyadstatus = "";\nfunction fix_stickyad() {\n  document.getElementById("stickypos").style.position = "sticky";\n  var elem = document.getElementById("stickyadcontainer");\n  if (!elem) {return false;}\n  if (document.getElementById("skyscraper")) {\n    var skyWidth = Number(w3_getStyleValue(document.getElementById("skyscraper"), "width").replace("px", ""));\n    if (isNaN(skyWidth) && document.getElementById("upperfeatureshowcaselink").parentElement) {\n      skyWidth = Number(w3_getStyleValue(document.getElementById("upperfeatureshowcaselink").parentElement, "width").replace("px", ""));\n    }\n  }\n  else {\n    var skyWidth = Number(w3_getStyleValue(document.getElementById("right"), "width").replace("px", ""));  \n  }\n  elem.style.width = skyWidth + "px";\n  if (window.innerWidth <= 992) {\n    elem.style.position = "";\n    elem.style.top = stickypos + "px";\n    return false;\n  }\n  var stickypos = document.getElementById("stickypos").offsetTop;\n  var docTop = window.pageYOffset || document.documentElement.scrollTop || document.body.scrollTop;\n  var adHeight = Number(w3_getStyleValue(elem, "height").replace("px", ""));\n  if (stickyadstatus == "") {\n    if ((stickypos - docTop) < 100) {\n      elem.style.position = "fixed";\n      elem.style.top = "100px";\n      stickyadstatus = "sticky";\n      document.getElementById("stickypos").style.position = "sticky";\n\n    }\n  } else {\n    if ((docTop + 100) - stickypos < 0) {  \n      elem.style.position = "";\n      elem.style.top = stickypos + "px";\n      stickyadstatus = "";\n      document.getElementById("stickypos").style.position = "static";\n    }\n  }\n  if (stickyadstatus == "sticky") {\n    if ((docTop + adHeight + 100) > document.getElementById("footer").offsetTop) {\n      elem.style.position = "absolute";\n      elem.style.top = (document.getElementById("footer").offsetTop - adHeight) + "px";\n      document.getElementById("stickypos").style.position = "static";\n    } else {\n        elem.style.position = "fixed";\n        elem.style.top = "100px";\n        stickyadstatus = "sticky";\n        document.getElementById("stickypos").style.position = "sticky";\n    }\n  }\n}\nfunction w3_getStyleValue(elmnt,style) {\n  if (window.getComputedStyle) {\n    return window.getComputedStyle(elmnt,null).getPropertyValue(style);\n  } else {\n    return elmnt.currentStyle[style];\n  }\n}\n</script>\n\n<script src="/lib/common-deps/main.v1.0.18.js"></script>\n<script src="/lib/user-session/main.v1.0.51.js"></script>\n<script src="/lib/topnav/main.v1.0.100.js"></script>\n<script src="/lib/my-learning/main.v1.0.86.js"></script>\n\n<style>\ntable#customers {\n    font-family: arial, sans-serif;\n    border-collapse: collapse;\n    width: 100%;\n}\n\n#customers td, #customers th {\n    border: 1px solid #dddddd;\n    text-align: left;\n    padding: 8px;\n}\n\n.tryiticon {\n  background-color: #4CAF50;\n  color: #fff!important;\n  text-decoration: none;\n  padding: 0 8px 4px 8px;\n  border-radius: 50px;\n  font-size: 15px;\n  position: absolute;\n  margin-left: 6px;\n  transition: padding 0.2s;\n  \n}\n.tryiticon span{\n  color:#fff!important;\n  font-size:14px;\n  font-weight:normal;\n  position:absolute;\n  width:0px;\n  overflow:hidden;\n  transition: width 0.2;\n}\n\n.tryiticon:hover {\n  padding:0 12px 4px 116px;\n}\n\n.tryiticon:hover span{\n  width:116px;\n  padding-top:2px;\n  left:10px;\n}\n\n.htmltut_table, .htmltut_table th, .htmltut_table td\n{\nborder:1px solid black;\n}\n.htmltut_table1, .htmltut_table1 th, .htmltut_table1 td\n{\nborder:1px solid black;\n}\n.htmltut_table1 th, .htmltut_table1 td\n{\npadding:5px;\n}\n</style>\n</head>\n<body>\n\n<div id="tnb-search-suggestions"></div>\n<div\n  id="top-nav-bar"\n  class="classic"\n>\n  <div\n    id="pagetop"\n    class="w3-bar notranslate w3-white"\n  >\n    <a\n      id="w3-logo"\n      href="https://www.w3schools.com"\n      class="w3-bar-item w3-button w3-hover-none w3-left ga-top ga-top-w3home"\n      title="Home"\n      aria-label="Home link"\n    >\n      <i\n        class="fa fa-logo ws-hover-text-green"\n        aria-hidden="true"\n      ></i>\n    </a>\n    <nav class="tnb-desktop-nav w3-bar-item">\n      <a\n        onclick="TopNavBar.openNavItem(\'tutorials\')"\n        class="tnb-nav-btn w3-bar-item w3-button barex bar-item-hover w3-padding-16 ga-top ga-top-tut-and-ref"\n        href="javascript:void(0)"\n        id="navbtn_tutorials"\n        title="Tutorials and References"\n        role="button"\n      >\n        Tutorials\n        <i\n          class="fa fa-caret-down"\n          style="font-size: 15px"\n          aria-hidden="true"\n        ></i>\n        <i\n          class="fa fa-caret-up"\n          style="display: none; font-size: 15px"\n          aria-hidden="true"\n        ></i>\n      </a>\n      <a\n        onclick="TopNavBar.openNavItem(\'references\')"\n        class="tnb-nav-btn w3-bar-item w3-button barex bar-item-hover w3-padding-16 ga-top ga-top-ref"\n        href="javascript:void(0)"\n        id="navbtn_references"\n        title="References"\n        role="button"\n      >\n        References\n        <i\n          class="fa fa-caret-down"\n          style="font-size: 15px"\n          aria-hidden="true"\n        ></i>\n        <i\n          class="fa fa-caret-up"\n          style="display: none; font-size: 15px"\n          aria-hidden="true"\n        ></i>\n      </a>\n      <a\n        onclick="TopNavBar.openNavItem(\'exercises\')"\n        class="tnb-nav-btn w3-bar-item w3-button barex bar-item-hover w3-padding-16 ga-top ga-top-exc-and-quz"\n        href="javascript:void(0)"\n        id="navbtn_exercises"\n        title="Exercises and Quizzes"\n        role="button"\n      >\n        Exercises\n        <i\n          class="fa fa-caret-down"\n          style="font-size: 15px"\n          aria-hidden="true"\n        ></i>\n        <i\n          class="fa fa-caret-up"\n          style="display: none; font-size: 15px"\n          aria-hidden="true"\n        ></i>\n      </a>\n      <a\n        onclick="TopNavBar.openNavItem(\'certified\')"\n        class="tnb-nav-btn w3-bar-item w3-button barex bar-item-hover w3-padding-16 tnb-paid-service ga-top ga-top-cert-and-course"\n        href="javascript:void(0)"\n        id="navbtn_certified"\n        title="Certificates"\n        role="button"\n      >\n        Certificates\n        <i\n          class="fa fa-caret-down"\n          style="font-size: 15px"\n          aria-hidden="true"\n        ></i>\n        <i\n          class="fa fa-caret-up"\n          style="display: none; font-size: 15px"\n          aria-hidden="true"\n        ></i>\n      </a>\n    </nav>\n    <a\n      onclick="TopNavBar.openMenu()"\n      class="tnb-menu-btn w3-bar-item w3-button bar-item-hover w3-padding-16 ga-top ga-top-menu"\n      href="javascript:void(0)"\n      title="Menu"\n      aria-label="Menu"\n      role="button"\n    >\n      Menu\n      <i\n        class="fa fa-caret-down"\n        style="font-size: 15px"\n        aria-hidden="true"\n      ></i>\n      <i\n        class="fa fa-caret-up"\n        style="display: none; font-size: 15px"\n        aria-hidden="true"\n      ></i>\n    </a>\n    <div\n      id="tnb-google-search-container"\n      class="w3-bar-item"\n    >\n      <div id="tnb-google-search-inner-container">\n        <label\n          for="tnb-google-search-input"\n          class="tnb-soft-hide"\n        >\n          Search field\n        </label>\n        <input\n          id="tnb-google-search-input"\n          type="text"\n          placeholder="Search..."\n          autocomplete="off"\n          onkeydown="TopNavBar.googleSearchAttachKeyPressHandler(event)"\n          aria-label="Search field"\n          oninput="TopNavBar.searchWithSuggestions(this)"\n          onfocus="TopNavBar.searchWithSuggestions(this)"\n          onblur="TopNavBar.searchFieldLostFocus(event)"\n        />\n        <div\n          id="tnb-google-search-submit-btn"\n          class="tnb-button-light"\n          role="button"\n          aria-label="Button to search"\n          onclick="TopNavBar.googleSearchSubmit()"\n        >\n          <svg\n            id="tnb-google-search-icon"\n            viewBox="0 0 17 16"\n            fill="none"\n            xmlns="http://www.w3.org/2000/svg"\n          >\n            <path\n              d="M11.8153 10.3439C12.6061 9.2673 13.0732 7.9382 13.0732 6.5C13.0732 2.91015 10.163 0 6.57318 0C2.98333 0 0.0731812 2.91015 0.0731812 6.5C0.0731812 10.0899 2.98333 13 6.57318 13C8.01176 13 9.3412 12.5327 10.4179 11.7415L10.4171 11.7422C10.4466 11.7822 10.4794 11.8204 10.5156 11.8566L14.3661 15.7071C14.7566 16.0976 15.3898 16.0976 15.7803 15.7071C16.1708 15.3166 16.1708 14.6834 15.7803 14.2929L11.9298 10.4424C11.8936 10.4062 11.8553 10.3734 11.8153 10.3439ZM12.0732 6.5C12.0732 9.53757 9.61075 12 6.57318 12C3.53561 12 1.07318 9.53757 1.07318 6.5C1.07318 3.46243 3.53561 1 6.57318 1C9.61075 1 12.0732 3.46243 12.0732 6.5Z"\n              fill="black"\n            ></path>\n          </svg>\n        </div>\n      </div>\n      <div id="tnb-google-search-mobile-action-btns">\n        <div\n          id="tnb-google-search-mobile-show"\n          class="tnb-button"\n          onclick="TopNavBar.googleSearchShowMobileContainer()"\n          aria-label="Button to open search field"\n          role="button"\n        >\n          <svg\n            viewBox="0 0 17 16"\n            fill="none"\n            xmlns="http://www.w3.org/2000/svg"\n          >\n            <path\n              d="M11.8153 10.3439C12.6061 9.2673 13.0732 7.9382 13.0732 6.5C13.0732 2.91015 10.163 0 6.57318 0C2.98333 0 0.0731812 2.91015 0.0731812 6.5C0.0731812 10.0899 2.98333 13 6.57318 13C8.01176 13 9.3412 12.5327 10.4179 11.7415L10.4171 11.7422C10.4466 11.7822 10.4794 11.8204 10.5156 11.8566L14.3661 15.7071C14.7566 16.0976 15.3898 16.0976 15.7803 15.7071C16.1708 15.3166 16.1708 14.6834 15.7803 14.2929L11.9298 10.4424C11.8936 10.4062 11.8553 10.3734 11.8153 10.3439ZM12.0732 6.5C12.0732 9.53757 9.61075 12 6.57318 12C3.53561 12 1.07318 9.53757 1.07318 6.5C1.07318 3.46243 3.53561 1 6.57318 1C9.61075 1 12.0732 3.46243 12.0732 6.5Z"\n              fill="currentColor"\n            ></path>\n          </svg>\n        </div>\n        <div\n          id="tnb-google-search-mobile-close"\n          class="tnb-button"\n          onclick="TopNavBar.googleSearchHideMobileContainer()"\n          role="button"\n          aria-label="Close search field"\n        >\n          <i>&times;</i>\n        </div>\n      </div>\n    </div>\n    <div id="tnb-menu-toggle-wrapper">\n      <a\n        onclick="TopNavBar.openNavItem(\'services\')"\n        class="tnb-nav-btn w3-bar-item w3-button barex bar-item-hover ga-top ga-top-services w3-tooltip"\n        href="javascript:void(0)"\n        id="navbtn_services"\n        aria-label="All our services"\n        role="button"\n      >\n        <span\n          class="w3-text"\n          id="button-to-open-services"\n        >\n          See More\n        </span>\n        <svg\n          xmlns="http://www.w3.org/2000/svg"\n          viewBox="0 0 640 640"\n        >\n          <path d="M320 208C289.1 208 264 182.9 264 152C264 121.1 289.1 96 320 96C350.9 96 376 121.1 376 152C376 182.9 350.9 208 320 208zM320 432C350.9 432 376 457.1 376 488C376 518.9 350.9 544 320 544C289.1 544 264 518.9 264 488C264 457.1 289.1 432 320 432zM376 320C376 350.9 350.9 376 320 376C289.1 376 264 350.9 264 320C264 289.1 289.1 264 320 264C350.9 264 376 289.1 376 320z" />\n        </svg>\n        <span style="font-size: 120px">&nbsp;</span>\n        <i aria-hidden="true"></i>\n        <i aria-hidden="true"></i>\n      </a>\n    </div>\n    <div class="tnb-right-section">\n      <!-- < user-anonymous -->\n      <div\n        id="tnb-login-btn"\n        class="user-anonymous tnb-login-btn w3-bar-item w3-btn w3-hide bar-item-hover w3-right w3s-green ga-top ga-top-login"\n        title="Sign in to your account"\n        aria-label="Sign in to your account"\n        tabindex="0"\n        role="button"\n      >\n        <svg\n          width="14"\n          height="14"\n          viewBox="0 0 14 14"\n          fill="none"\n          xmlns="http://www.w3.org/2000/svg"\n          class="tnb-sign-in-icon"\n        >\n          <path\n            d="M7 7C8.933 7 10.5 5.433 10.5 3.5C10.5 1.567 8.933 0 7 0C5.067 0 3.5 1.567 3.5 3.5C3.5 5.433 5.067 7 7 7ZM9.33333 3.5C9.33333 4.78866 8.28866 5.83333 7 5.83333C5.71134 5.83333 4.66667 4.78866 4.66667 3.5C4.66667 2.21134 5.71134 1.16667 7 1.16667C8.28866 1.16667 9.33333 2.21134 9.33333 3.5Z"\n            fill="white"\n          />\n          <path\n            d="M14 12.8333C14 14 12.8333 14 12.8333 14H1.16667C1.16667 14 0 14 0 12.8333C0 11.6667 1.16667 8.16667 7 8.16667C12.8333 8.16667 14 11.6667 14 12.8333ZM12.8333 12.8293C12.8316 12.5414 12.6539 11.6789 11.8625 10.8875C11.1016 10.1265 9.67062 9.33333 6.99999 9.33333C4.32936 9.33333 2.89841 10.1265 2.13745 10.8875C1.34605 11.6789 1.16833 12.5414 1.16

### 轉成DataFrame

接下來的步驟，我們要將文字檔中的table轉成DataFrame，主要可以分成兩個步驟：

- 存成 html 檔
- 用 pandas 讀取 html 檔

In [17]:
# 存檔

f = open('test.html', 'w', encoding='utf-8')
f.write(res.text)
f.close()

In [22]:
# 讀檔並轉成DataFrame

import pandas as pd

dfs = pd.read_html('test.html')

In [27]:
# 瀏覽
dfs[0]

                        Company           Contact  Country
0           Alfreds Futterkiste      Maria Anders  Germany
1    Centro comercial Moctezuma   Francisco Chang   Mexico
2                  Ernst Handel     Roland Mendel  Austria
3                Island Trading     Helen Bennett       UK
4  Laughing Bacchus Winecellars   Yoshi Tannamuri   Canada
5  Magazzini Alimentari Riuniti  Giovanni Rovelli    Italy

### 轉成DataFrame（快速版）

其實也可以只寫成一個步驟（但還是建議先存起來）

In [25]:
# 不存檔直接轉成DataFrame
from io import StringIO

dfs = pd.read_html(StringIO(res.text))
dfs[0]

                        Company           Contact  Country
0           Alfreds Futterkiste      Maria Anders  Germany
1    Centro comercial Moctezuma   Francisco Chang   Mexico
2                  Ernst Handel     Roland Mendel  Austria
3                Island Trading     Helen Bennett       UK
4  Laughing Bacchus Winecellars   Yoshi Tannamuri   Canada
5  Magazzini Alimentari Riuniti  Giovanni Rovelli    Italy